name:                haskpet
version:             0.1.0.0
github:              "iLnurr/haskpet"
license:             BSD3
author:              "ilnur serbaev"
maintainer:          "serbaevilnur@gmail.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iLnurr/haskpet#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- aeson
- data-default-class
- monad-logger
- resourcet
- mtl
- persistent
- persistent-sqlite
- persistent-template
- json-rpc-server
- yesod-core
- yesod

default-extensions:
  OverloadedStrings, QuasiQuotes, TemplateHaskell, TypeFamilies, ViewPatterns, ExtendedDefaultRules, RecordWildCards, DeriveGeneric, EmptyDataDecls, FlexibleContexts, FlexibleInstances, GADTs, GeneralizedNewtypeDeriving, MultiParamTypeClasses

library:
  source-dirs: src

executables:
  haskpet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskpet

tests:
  haskpet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskpet
